//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpaLib.Tests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpaLib.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0‚[	*†H†÷        /// ‚L0‚H10	+ 0‚!	*†H†÷        /// ‚‚&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;AppIDName&lt;/key&gt;
        ///	&lt;string&gt;Xcode iOS Wildcard App ID&lt;/string&gt;
        ///	&lt;key&gt;ApplicationIdentifierPrefix&lt;/key&gt;
        ///	&lt;array&gt;
        ///	&lt;string&gt;FFFFFFFFV&lt;/string&gt;
        ///	&lt;/array&gt;
        ///	&lt;key&gt;CreationDate&lt;/key&gt;
        ///	&lt;date&gt;2015-07-21T18:03:24Z&lt;/date&gt;
        ///	&lt;key&gt;Platform&lt;/key&gt;
        ///	&lt;array&gt;
        ///		&lt;string&gt;iOS&lt;/string&gt;
        ///	&lt;/array&gt;
        ///	&lt;k [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SampleBrowser_embeddedmobileprovision {
            get {
                return ResourceManager.GetString("SampleBrowser_embeddedmobileprovision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///	&lt;key&gt;genre&lt;/key&gt;
        ///	&lt;string&gt;Application&lt;/string&gt;
        ///	&lt;key&gt;bundleVersion&lt;/key&gt;
        ///	&lt;string&gt;1.0&lt;/string&gt;
        ///	&lt;key&gt;itemName&lt;/key&gt;
        ///	&lt;string&gt;SampleBrowser&lt;/string&gt;
        ///	&lt;key&gt;kind&lt;/key&gt;
        ///	&lt;string&gt;software&lt;/string&gt;
        ///	&lt;key&gt;playlistName&lt;/key&gt;
        ///	&lt;string&gt;SampleBrowser&lt;/string&gt;
        ///	&lt;key&gt;softwareIconNeedsShine&lt;/key&gt;
        ///	&lt;true/&gt;
        ///	&lt;key&gt;softwareVersionBundleId&lt;/key&gt;
        ///	&lt;string&gt;co [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SampleBrowser_itunesmetadata {
            get {
                return ResourceManager.GetString("SampleBrowser_itunesmetadata", resourceCulture);
            }
        }
    }
}
